/**
 * Configuration constants for the OpenAPI generator
 */

export const HTTP_SUCCESS_STATUSES = ['200', '201', '202', '204', '205', '206', '207', '208'] as const;

export const PRIMITIVE_TYPES = ['String', 'Number', 'Boolean', 'Array', 'Object'];

export const DEFAULT_PATHS = {
  OPENAPI: './openapi.yaml',
  GENERATED_DIR: './node_modules/@generated',
  MIDDLEWARE_CONFIG: './middleware-config.js',
} as const;

export const FOLDER_NAMES = {
  CONTROLLERS: 'controllers',
  MODELS: 'models',
  ROUTES: 'routes',
} as const;

// Content type constants
export const CONTENT_TYPE = {
  JSON: 'application/json',
} as const;

// Parameter type naming configuration
export const MAX_PARAM_NAME_COMBINATION = 3; // Maximum parameters to combine in type name before using fallback

// Regex patterns for type dependency extraction
export const TYPE_DEPENDENCY_PATTERNS = {
  PROPERTY_TYPE: /:\s*([A-Z][a-zA-Z0-9]*(?:\[])?)/g,
  TYPE_ALIAS: /=\s*([A-Z][a-zA-Z0-9]*(?:\[])?)/g,
  TYPE_DECLARATION: /(?:export\s+)?(?:interface|type|enum)\s+(\w+)/,
} as const;

// File header templates
export const FILE_HEADERS = {
  MODEL: (typeName: string) => `/**\n * ${typeName} model - Auto-generated from OpenAPI specification\n */`,
  MODELS_INDEX: `/**\n * Models index - Auto-generated exports from OpenAPI specification\n * Generated by generate.ts\n */`,
  ROUTES: (tag: string) => `/**\n * Auto-generated ${tag} routes from OpenAPI specification\n * Generated by generate.ts\n */`,
} as const;

// Default fallback for unknown schema names
export const UNKNOWN_TYPE = 'Unknown' as const;
